name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install modules
        run: bun install --frozen-lockfile
      - name: Run ESLint
        run: bun run lint
